# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Save-Home
version:      0.03
version_from: lib/File/Save/Home.pm
installdirs:  site
requires:
    Carp:                          0
    File::Path:                    0
    File::Spec:                    0
    File::Temp:                    0
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
